modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="drop_guard"
version="1.2"
displayName="Drop Guard"
authors="Tj"
description='''Prevents accidental item drops in the world while leaving inventory dropping untouched.'''

[[mixins]]
config="mixins.drop_guard.json"

[[dependencies.drop_guard]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.drop_guard]]
modId="neoforge"
type="required"
versionRange="[21.1,22)"
ordering="NONE"
side="CLIENT"
